# sweep.yaml
# This is your "Search Space" config

method: bayes
metric:
  name: eval/loss
  goal: minimize

program: /data/home/qc25022/CancEHR-Training/src/experiments/run_llm_pretrain.py

command:
  - ${env}         # Sets up environment variables
  - ${interpreter}  # Calls 'python'
  - ${program}      # Calls your main.py script
  - --config_filepath   # Your script's required argument
  - /data/home/qc25022/CancEHR-Training/src/experiments/configs/llm_pretrain.yaml

parameters:
  # 1. Tune Training Hyperparameters
  training.learning_rate:
    distribution: log_uniform_values
    min: 1e-6
    max: 5e-5

  training.weight_decay:
    values: [0.01, 0.05, 0.1]
  
  training.gradient_accumulation_steps:
    values: [1, 2, 4]
  
  # 2. Tune LoRA Hyperparameters
  lora.r:
    values: [8, 16]
  
  lora.lora_dropout:
    values: [0.05, 0.1, 0.2]

  # 3. Set Epochs to 1 for fast experiments
  training.epochs:
    value: 1